import nodemailer from 'nodemailer';
import { NegativeFeedbackEmailData, EmailTemplate } from './types';

// Email configuration
const transporter = nodemailer.createTransporter({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

export async function sendEmail(to: string, subject: string, html: string, text?: string): Promise<void> {
  try {
    await transporter.sendMail({
      from: `"Vanterra Reviews" <${process.env.SMTP_USER}>`,
      to,
      subject,
      html,
      text: text || html.replace(/<[^>]*>/g, ''), // Strip HTML tags for text version
    });
  } catch (error) {
    console.error('Failed to send email:', error);
    throw new Error('Failed to send email');
  }
}

export function generateNegativeFeedbackEmail(data: NegativeFeedbackEmailData): EmailTemplate {
  const subject = `Negative Review Alert - ${data.brandName} (${data.locationName})`;
  
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${subject}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          background: #dc2626;
          color: white;
          padding: 20px;
          border-radius: 8px 8px 0 0;
          text-align: center;
        }
        .content {
          background: #f9fafb;
          padding: 30px;
          border: 1px solid #e5e7eb;
          border-top: none;
        }
        .customer-info {
          background: white;
          padding: 20px;
          border-radius: 8px;
          margin: 20px 0;
          border-left: 4px solid #dc2626;
        }
        .rating {
          display: inline-block;
          background: #dc2626;
          color: white;
          padding: 4px 12px;
          border-radius: 20px;
          font-weight: bold;
          font-size: 14px;
        }
        .comments {
          background: white;
          padding: 15px;
          border-radius: 6px;
          border: 1px solid #e5e7eb;
          margin: 15px 0;
          font-style: italic;
        }
        .action-button {
          display: inline-block;
          background: #059669;
          color: white;
          padding: 12px 24px;
          text-decoration: none;
          border-radius: 6px;
          font-weight: bold;
          margin: 20px 0;
        }
        .footer {
          text-align: center;
          color: #6b7280;
          font-size: 14px;
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
        }
        .emoji {
          font-size: 24px;
          margin-right: 10px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🚨 Negative Review Alert</h1>
        <p><strong>${data.brandName}</strong> - ${data.locationName}</p>
      </div>
      
      <div class="content">
        <p>A customer has submitted negative feedback that requires your immediate attention.</p>
        
        <div class="customer-info">
          <h3>Customer Information</h3>
          <p><strong>Name:</strong> ${data.customerName}</p>
          <p><strong>Email:</strong> ${data.customerEmail}</p>
          <p><strong>Phone:</strong> ${data.customerPhone}</p>
          <p><strong>Rating:</strong> <span class="rating">${data.rating}/5</span></p>
        </div>
        
        <h3>Customer Comments</h3>
        <div class="comments">
          "${data.comments}"
        </div>
        
        <p><strong>Action Required:</strong> Please contact this customer within 24 hours to address their concerns and resolve the issue.</p>
        
        <div style="text-align: center;">
          <a href="${data.reviewUrl}" class="action-button">View Full Review Details</a>
        </div>
        
        <p><strong>Next Steps:</strong></p>
        <ul>
          <li>Contact the customer within 24 hours</li>
          <li>Address their specific concerns</li>
          <li>Document the resolution in your system</li>
          <li>Follow up to ensure satisfaction</li>
        </ul>
      </div>
      
      <div class="footer">
        <p>This notification was automatically generated by Vanterra Reviews.</p>
        <p>Please respond promptly to maintain customer satisfaction.</p>
      </div>
    </body>
    </html>
  `;

  const text = `
    NEGATIVE REVIEW ALERT - ${data.brandName} (${data.locationName})
    
    A customer has submitted negative feedback that requires your immediate attention.
    
    Customer Information:
    - Name: ${data.customerName}
    - Email: ${data.customerEmail}
    - Phone: ${data.customerPhone}
    - Rating: ${data.rating}/5
    
    Customer Comments:
    "${data.comments}"
    
    Action Required: Please contact this customer within 24 hours to address their concerns and resolve the issue.
    
    View Full Review Details: ${data.reviewUrl}
    
    Next Steps:
    - Contact the customer within 24 hours
    - Address their specific concerns
    - Document the resolution in your system
    - Follow up to ensure satisfaction
    
    This notification was automatically generated by Vanterra Reviews.
    Please respond promptly to maintain customer satisfaction.
  `;

  return { subject, html, text };
}

export async function sendNegativeFeedbackNotification(data: NegativeFeedbackEmailData): Promise<void> {
  const emailTemplate = generateNegativeFeedbackEmail(data);
  await sendEmail(data.notificationEmail, emailTemplate.subject, emailTemplate.html, emailTemplate.text);
}

export async function sendPasswordResetEmail(email: string, resetUrl: string): Promise<void> {
  const subject = 'Password Reset Request - Vanterra Reviews';
  
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${subject}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          background: #059669;
          color: white;
          padding: 20px;
          border-radius: 8px 8px 0 0;
          text-align: center;
        }
        .content {
          background: #f9fafb;
          padding: 30px;
          border: 1px solid #e5e7eb;
          border-top: none;
        }
        .reset-button {
          display: inline-block;
          background: #059669;
          color: white;
          padding: 12px 24px;
          text-decoration: none;
          border-radius: 6px;
          font-weight: bold;
          margin: 20px 0;
        }
        .footer {
          text-align: center;
          color: #6b7280;
          font-size: 14px;
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🔐 Password Reset Request</h1>
        <p>Vanterra Reviews Admin Panel</p>
      </div>
      
      <div class="content">
        <p>You requested a password reset for your Vanterra Reviews admin account.</p>
        
        <p>Click the button below to reset your password. This link will expire in 1 hour.</p>
        
        <div style="text-align: center;">
          <a href="${resetUrl}" class="reset-button">Reset Password</a>
        </div>
        
        <p>If you didn't request this password reset, please ignore this email or contact support if you have concerns.</p>
        
        <p><strong>Security Note:</strong> This link can only be used once and will expire after 1 hour.</p>
      </div>
      
      <div class="footer">
        <p>This email was sent from Vanterra Reviews.</p>
        <p>If you need assistance, please contact your system administrator.</p>
      </div>
    </body>
    </html>
  `;

  const text = `
    PASSWORD RESET REQUEST - Vanterra Reviews Admin Panel
    
    You requested a password reset for your Vanterra Reviews admin account.
    
    Click the link below to reset your password. This link will expire in 1 hour.
    
    ${resetUrl}
    
    If you didn't request this password reset, please ignore this email or contact support if you have concerns.
    
    Security Note: This link can only be used once and will expire after 1 hour.
    
    This email was sent from Vanterra Reviews.
    If you need assistance, please contact your system administrator.
  `;

  await sendEmail(email, subject, html, text);
}
